
[functions.ma-fonction]
enabled = true
verify_jwt = false
import_map = "./functions/ma-fonction/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ma-fonction/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ma-fonction/*.html" ]

