name: Scrape OnePiece Chapters

on:
  schedule:
    - cron: '0 4 * * *' # Tous les jours à 4h du matin UTC
  workflow_dispatch: # Permet aussi de le lancer manuellement

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Cloner le repo
        uses: actions/checkout@v3

      - name: 🟨 Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Installer les dépendances
        run: npm install

      - name: 🚀 Exécuter le script de scraping
        run: |
          cd src/Onepiece
          ls
          npx tsx index.ts
